# PFE : Analyse de données statistiques sportives

## II. Cleaning des données

Comme vous le savez, avant d'effectuer une prédiction sur une variable que l'on souhaite prédire, une des phases fondamentale d'un Data Scientist est le Cleaning.
Nous allons par conséquent effectuer un nombre de modification sur notre Dataset pour optimiser la prédiciton de nos algorithmes.
Le but ici serait de clean les datasets :
- MVPS 
- PLAYERS
- TEAMS

Afin faire un merge final et enfin pouvoir faire nos prediction sur un même et unique fichier

## CODE

### Import des librairies nécessaires

In [22]:
import pandas as pd
import sqlite3
import re

### Lecture des fichiers SQLite

In [23]:
path = ""
databaseMVP = path + 'mvp.sqlite'
MVPcon = sqlite3.connect(databaseMVP)

In [24]:
MVPS = pd.read_sql("""SELECT * from MVP""", MVPcon)

In [5]:
path = ""
databasePLAYERS = path + 'players.sqlite'
PLAYERScon = sqlite3.connect(databasePLAYERS)

In [6]:
PLAYERS = pd.read_sql("""SELECT * from PLAYERS""", PLAYERScon)

In [7]:
path = ""
databaseTEAMS = path + 'teams.sqlite'
TEAMScon = sqlite3.connect(databaseTEAMS)

In [8]:
TEAMS = pd.read_sql("""SELECT * from TEAMS""", TEAMScon)

### Clean du dataset MVPS

In [9]:
MVPS

,index,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Kareem Abdul-Jabbar,32,LAL,147.0,147.0,221,0.665,82,...,10.8,4.5,1.0,3.4,0.604,0.000,0.765,14.8,0.227,1980
1,1,2,Julius Erving,29,PHI,31.5,31.5,221,0.143,78,...,7.4,4.6,2.2,1.8,0.519,0.200,0.787,12.5,0.213,1980
2,2,3,George Gervin,27,SAS,19.0,19.0,221,0.086,78,...,5.2,2.6,1.4,1.0,0.528,0.314,0.852,10.6,0.173,1980
3,3,4,Larry Bird,23,BOS,15.0,15.0,221,0.068,82,...,10.4,4.5,1.7,0.6,0.474,0.406,0.836,11.2,0.182,1980
4,4,5T,Tiny Archibald,31,BOS,2.0,2.0,221,0.009,80,...,2.5,8.4,1.3,0.1,0.482,0.222,0.830,8.9,0.148,1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,7,8,Stephen Curry,33,GSW,0.0,4.0,1000,0.004,64,...,5.2,6.3,1.3,0.4,0.437,0.380,0.923,8.0,0.173,2022
705,8,9,Chris Paul,36,PHO,0.0,2.0,1000,0.002,65,...,4.4,10.8,1.9,0.3,0.493,0.317,0.837,9.4,0.210,2022
706,9,10T,DeMar DeRozan,32,CHI,0.0,1.0,1000,0.001,76,...,5.2,4.9,0.9,0.3,0.504,0.352,0.877,8.8,0.154,2022
707,10,10T,Kevin Durant,33,BRK,0.0,1.0,1000,0.001,55,...,7.4,6.4,0.9,0.9,0.518,0.383,0.910,8.4,0.198,2022
708,11,10T,LeBron James,37,LAL,0.0,1.0,1000,0.001,56,...,8.2,6.2,1.3,1.1,0.524,0.359,0.756,7.5,0.172,2022

#### Nous pouvons voir ici que les colonnes sur les statistiques ne servent pas à grande chose en raison de leur présence dans le dataset player, nous allons par conséquent garder uniquement les colonnes necessaire à ce dataset

In [25]:
MVPS = MVPS[["Player", "Year", "Pts Won", "Pts Max", "Share"]]

In [18]:
MVPS

                  Player  Year  Pts Won  Pts Max  Share
0    Kareem Abdul-Jabbar  1980    147.0      221  0.665
1          Julius Erving  1980     31.5      221  0.143
2          George Gervin  1980     19.0      221  0.086
3             Larry Bird  1980     15.0      221  0.068
4         Tiny Archibald  1980      2.0      221  0.009
..                   ...   ...      ...      ...    ...
704        Stephen Curry  2022      4.0     1000  0.004
705           Chris Paul  2022      2.0     1000  0.002
706        DeMar DeRozan  2022      1.0     1000  0.001
707         Kevin Durant  2022      1.0     1000  0.001
708         LeBron James  2022      1.0     1000  0.001

[709 rows x 5 columns]

### Clean du dataset PLAYERS

In [19]:
PLAYERS

,index,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,0,1,Kareem Abdul-Jabbar*,C,32,LAL,82,NaN,38.3,10.2,...,2.3,8.5,10.8,4.5,1.0,3.4,3.6,2.6,24.8,1980
1,1,2,Tom Abernethy,PF,25,GSW,67,NaN,18.2,2.3,...,0.9,1.9,2.9,1.3,0.5,0.2,0.6,1.8,5.4,1980
2,2,3,Alvan Adams,C,25,PHO,75,NaN,28.9,6.2,...,2.1,6.0,8.1,4.3,1.4,0.7,2.9,3.2,14.9,1980
3,3,4,Tiny Archibald*,PG,31,BOS,80,80.0,35.8,4.8,...,0.7,1.7,2.5,8.4,1.3,0.1,3.0,2.7,14.1,1980
4,4,5,Dennis Awtrey,C,31,CHI,26,NaN,21.5,1.0,...,1.1,3.3,4.4,1.5,0.5,0.6,1.0,2.5,3.3,1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23113,646,515,Thaddeus Young,PF,34,TOR,54,9.0,14.7,2.0,...,1.3,1.8,3.1,1.4,1.0,0.1,0.8,1.6,4.4,2023
23114,647,516,Trae Young,PG,24,ATL,62,62.0,35.0,8.6,...,0.8,2.2,3.0,10.1,1.1,0.1,4.1,1.5,27.0,2023
23115,648,517,Omer Yurtseven,C,24,MIA,3,0.0,8.3,1.0,...,0.7,1.0,1.7,0.0,0.0,0.3,0.0,2.0,2.3,2023
23116,649,518,Cody Zeller,C,30,MIA,10,0.0,13.0,1.5,...,1.6,1.9,3.5,0.6,0.2,0.4,0.8,2.3,4.7,2023
23117,650,519,Ivica Zubac,C,25,LAC,64,64.0,29.1,4.1,...,3.3,6.8,10.1,1.1,0.4,1.3,1.7,2.9,10.4,2023

#### Nous pouvons voir ici que les colonnes "index", "Rk" ne servent à rien à l'intérêt du dataset qui est censé nous répertorier les statistiques de chaque joueur sur une année

In [10]:
PLAYERS.drop(columns = ["index","Rk"], inplace = True)

In [21]:
PLAYERS

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Kareem Abdul-Jabbar*,C,32,LAL,82,NaN,38.3,10.2,16.9,0.604,...,2.3,8.5,10.8,4.5,1.0,3.4,3.6,2.6,24.8,1980
1,Tom Abernethy,PF,25,GSW,67,NaN,18.2,2.3,4.7,0.481,...,0.9,1.9,2.9,1.3,0.5,0.2,0.6,1.8,5.4,1980
2,Alvan Adams,C,25,PHO,75,NaN,28.9,6.2,11.7,0.531,...,2.1,6.0,8.1,4.3,1.4,0.7,2.9,3.2,14.9,1980
3,Tiny Archibald*,PG,31,BOS,80,80.0,35.8,4.8,9.9,0.482,...,0.7,1.7,2.5,8.4,1.3,0.1,3.0,2.7,14.1,1980
4,Dennis Awtrey,C,31,CHI,26,NaN,21.5,1.0,2.3,0.450,...,1.1,3.3,4.4,1.5,0.5,0.6,1.0,2.5,3.3,1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23113,Thaddeus Young,PF,34,TOR,54,9.0,14.7,2.0,3.7,0.545,...,1.3,1.8,3.1,1.4,1.0,0.1,0.8,1.6,4.4,2023
23114,Trae Young,PG,24,ATL,62,62.0,35.0,8.6,19.7,0.436,...,0.8,2.2,3.0,10.1,1.1,0.1,4.1,1.5,27.0,2023
23115,Omer Yurtseven,C,24,MIA,3,0.0,8.3,1.0,2.0,0.500,...,0.7,1.0,1.7,0.0,0.0,0.3,0.0,2.0,2.3,2023
23116,Cody Zeller,C,30,MIA,10,0.0,13.0,1.5,2.9,0.517,...,1.6,1.9,3.5,0.6,0.2,0.4,0.8,2.3,4.7,2023
23117,Ivica Zubac,C,25,LAC,64,64.0,29.1,4.1,6.5,0.627,...,3.3,6.8,10.1,1.1,0.4,1.3,1.7,2.9,10.4,2023

#### Un autre soucis qui peut être posé quand nous allons merge les datasets, serait la présence d'astérisque à la fin des joueurs qui ne sont pas présentes dans les autres dataset.

In [22]:
PLAYERS["Player"].head(50)

0     Kareem Abdul-Jabbar*
1            Tom Abernethy
2              Alvan Adams
3          Tiny Archibald*
4            Dennis Awtrey
5               Gus Bailey
6             James Bailey
7             Greg Ballard
8              Mike Bantom
9            Marvin Barnes
10             Rick Barry*
11             Tim Bassett
12             Tim Bassett
13             Tim Bassett
14         Billy Ray Bates
15             Ron Behagen
16             Kent Benson
17             Kent Benson
18             Kent Benson
19             Del Beshore
20             Henry Bibby
21             Larry Bird*
22           Otis Birdsong
23               Ron Boone
24               Ron Boone
25               Ron Boone
26         Lawrence Boston
27             Tom Boswell
28             Tom Boswell
29             Tom Boswell
30          Winford Boynes
31          Alonzo Bradley
32          Dudley Bradley
33              Mike Bratz
34              Jim Brewer
35              Ron Brewer
36        Junior Bridgeman
37           Allan Bristow
38              Fred Brown
39              John Brown
40              John Brown
41              John Brown
42             Roger Brown
43              Joe Bryant
44           Quinn Buckner
45            Tom Burleson
46                Don Buse
47            Marty Byrnes
48           Corky Calhoun
49             Mack Calvin
Name: Player, dtype: object

#### L'idée serait donc tout simplement de les enlever pour nous faciliter le merge

In [11]:
PLAYERS["Player"] = PLAYERS["Player"].str.replace("*", "", regex = False)

In [24]:
PLAYERS.head(20)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Kareem Abdul-Jabbar,C,32,LAL,82,NaN,38.3,10.2,16.9,0.604,...,2.3,8.5,10.8,4.5,1.0,3.4,3.6,2.6,24.8,1980
1,Tom Abernethy,PF,25,GSW,67,NaN,18.2,2.3,4.7,0.481,...,0.9,1.9,2.9,1.3,0.5,0.2,0.6,1.8,5.4,1980
2,Alvan Adams,C,25,PHO,75,NaN,28.9,6.2,11.7,0.531,...,2.1,6.0,8.1,4.3,1.4,0.7,2.9,3.2,14.9,1980
3,Tiny Archibald,PG,31,BOS,80,80.0,35.8,4.8,9.9,0.482,...,0.7,1.7,2.5,8.4,1.3,0.1,3.0,2.7,14.1,1980
4,Dennis Awtrey,C,31,CHI,26,NaN,21.5,1.0,2.3,0.450,...,1.1,3.3,4.4,1.5,0.5,0.6,1.0,2.5,3.3,1980
5,Gus Bailey,SG,28,WSB,20,NaN,9.0,0.8,1.8,0.457,...,0.3,1.1,1.4,1.3,0.4,0.2,0.6,0.9,1.9,1980
6,James Bailey,PF,22,SEA,67,NaN,10.8,1.8,4.0,0.450,...,1.1,1.9,2.9,0.4,0.3,0.8,1.2,1.7,4.7,1980
7,Greg Ballard,SF,25,WSB,82,NaN,29.7,6.6,13.4,0.495,...,2.9,4.9,7.8,1.9,1.1,0.4,1.6,2.4,15.6,1980
8,Mike Bantom,SF,28,IND,77,NaN,30.3,5.0,9.9,0.505,...,2.5,3.4,5.9,3.6,1.1,0.6,2.5,3.5,11.8,1980
9,Marvin Barnes,PF,27,SDC,20,NaN,14.4,1.2,3.0,0.400,...,1.7,2.2,3.9,0.9,0.3,0.6,0.9,2.6,3.2,1980
10,Rick Barry,SF,35,HOU,72,NaN,25.2,4.5,10.7,0.422,...,0.7,2.5,3.3,3.7,1.1,0.4,2.1,2.5,12.0,1980
11,Tim Bassett,PF,28,TOT,12,NaN,13.7,1.0,2.8,0.353,...,0.9,1.8,2.8,1.2,0.7,0.0,0.8,2.3,2.8,1980
12,Tim Bassett,PF,28,NJN,7,NaN,13.1,1.1,3.1,0.364,...,1.0,1.6,2.6,0.6,0.7,0.0,0.6,2.0,3.4,1980
13,Tim Bassett,PF,28,SAS,5,NaN,14.4,0.8,2.4,0.333,...,0.8,2.2,3.0,2.0,0.6,0.0,1.0,2.6,2.0,1980
14,Billy Ray Bates,SG,23,POR,16,NaN,14.7,4.5,9.1,0.493,...,0.8,1.0,1.8,1.9,0.9,0.1,1.3,1.6,11.3,1980
15,Ron Behagen,PF,29,WSB,6,NaN,10.7,1.5,3.8,0.391,...,1.0,1.3,2.3,1.2,0.0,0.7,0.7,2.3,3.8,1980
16,Kent Benson,C,25,TOT,73,NaN,25.9,4.1,8.5,0.484,...,1.7,4.5,6.2,2.4,1.0,1.3,2.2,3.4,9.6,1980
17,Kent Benson,C,25,MIL,56,NaN,24.8,3.8,7.7,0.494,...,1.7,4.2,5.9,2.3,1.0,1.3,1.9,3.2,8.8,1980
18,Kent Benson,C,25,DET,17,NaN,29.5,5.1,11.0,0.460,...,1.8,5.3,7.1,3.0,1.1,1.1,3.0,4.0,12.1,1980
19,Del Beshore,PG,23,CHI,68,NaN,12.8,1.3,3.7,0.352,...,0.2,0.7,0.9,2.0,0.9,0.1,1.5,1.5,3.6,1980

#### Lors de la lecture du dataframe PLAYERS nous pouvons remarquer que certains joueurs ont plusieurs lignes dans le dataframe sur une même année qui est dû au faite que ces joueurs ont joué dans plusieurs équipes différentes lors d'une même saison

#### L'idée ici serait uniquement de garder le statistiques globales sur l'année, donc nous allons nous intéresser à la valeur "Tm" = "TOT" qui correspond à la statistique globale d'un joueur sur une année

In [25]:
PLAYERS.loc[PLAYERS["Player"] == "George Johnson"]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
159,George Johnson,C,31,NJN,81,NaN,26.2,3.1,6.7,0.457,...,2.4,5.1,7.4,2.1,0.7,3.2,2.5,3.9,7.2,1980
160,George Johnson,PF,23,DEN,75,NaN,25.8,4.1,8.7,0.476,...,2.5,5.3,7.8,2.1,1.1,0.9,2.0,3.5,10.2,1980
513,George Johnson,C,32,SAS,82,NaN,23.6,2.0,4.2,0.473,...,2.6,4.7,7.3,1.1,0.6,3.4,1.3,3.3,5.0,1981
514,George Johnson,PF,24,IND,43,NaN,21.6,4.2,9.2,0.462,...,2.3,4.2,6.5,2.0,1.1,0.5,2.0,2.8,10.6,1981
879,George Johnson,C,33,SAS,75,62.0,21.0,1.2,2.6,0.467,...,2.0,4.0,6.1,1.1,0.3,3.1,1.2,3.5,3.0,1982
880,George Johnson,PF,25,IND,59,4.0,12.2,2.0,4.9,0.412,...,1.2,2.5,3.7,0.7,0.6,0.4,1.2,2.5,5.1,1982
1251,George Johnson,C,34,ATL,37,0.0,12.5,0.7,1.5,0.439,...,1.2,2.0,3.2,0.5,0.3,1.6,0.5,1.9,1.7,1983
1252,George Johnson,SF,26,IND,82,64.0,28.0,5.0,10.5,0.477,...,2.1,4.5,6.6,2.7,0.9,0.6,3.0,3.4,11.6,1983
1616,George Johnson,SF,27,IND,81,20.0,25.6,5.1,10.9,0.465,...,1.7,4.0,5.7,2.4,1.0,0.6,2.3,3.2,13.0,1984
1965,George Johnson,C,36,NJN,65,0.0,12.3,0.6,1.2,0.532,...,1.1,1.7,2.8,0.3,0.3,1.2,0.6,2.3,1.6,1985
1966,George Johnson,SF,28,PHI,55,3.0,13.7,1.9,4.8,0.407,...,0.9,2.1,3.0,0.7,0.6,0.3,0.9,1.8,4.8,1985
2346,George Johnson,C,37,SEA,41,0.0,6.4,0.3,0.6,0.522,...,0.6,0.8,1.5,0.3,0.1,0.9,0.3,1.1,0.9,1986
2347,George Johnson,PF,29,WSB,2,0.0,3.5,0.5,1.5,0.333,...,0.5,0.5,1.0,0.0,0.0,0.0,0.5,0.5,2.0,1986

In [12]:
def uniqueROW(df):
    if df.shape[0] == 1:
        return df
    else:
        row = df[df["Tm"] == "TOT"]
        row["Tm"] = df.iloc[-1,:]["Tm"]
        return row

PLAYERS = PLAYERS.groupby(["Player", "Year", "Pos"]).apply(uniqueROW)

In [27]:
PLAYERS

                                       Player Pos  Age   Tm   G    GS    MP  \
Player         Year Pos
A.C. Green     1986 PF  2302       A.C. Green  PF   22  LAL  82   1.0  18.8
               1987 PF  2686       A.C. Green  PF   23  LAL  79  72.0  28.4
               1988 PF  3072       A.C. Green  PF   24  LAL  82  64.0  32.1
               1989 PF  3506       A.C. Green  PF   25  LAL  82  82.0  30.6
               1990 PF  3951       A.C. Green  PF   26  LAL  82  82.0  33.0
...                                       ...  ..  ...  ...  ..   ...   ...
Željko Rebrača 2002 C   10135  Željko Rebrača   C   29  DET  74   4.0  15.9
               2003 C   10616  Željko Rebrača   C   30  DET  30  12.0  16.3
               2004 C   11176  Željko Rebrača   C   31  ATL  24   2.0  11.4
               2005 C   11754  Željko Rebrača   C   32  LAC  58   2.0  16.0
               2006 C   12326  Željko Rebrača   C   33  LAC  29   2.0  14.2

                                FG  FGA    FG%  ...  ORB  DRB  TRB  AST  STL  \
Player         Year Pos                         ...
A.C. Green     1986 PF  2302   2.5  4.7  0.539  ...  2.0  2.7  4.6  0.7  0.6
               1987 PF  2686   4.0  7.4  0.538  ...  2.7  5.1  7.8  1.1  0.9
               1988 PF  3072   3.9  7.8  0.503  ...  3.0  5.7  8.7  1.1  1.1
               1989 PF  3506   4.9  9.2  0.529  ...  3.1  5.9  9.0  1.3  1.1
               1990 PF  3951   4.7  9.8  0.478  ...  3.2  5.5  8.7  1.1  0.8
...                            ...  ...    ...  ...  ...  ...  ...  ...  ...
Željko Rebrača 2002 C   10135  2.6  5.1  0.505  ...  1.1  2.8  3.9  0.5  0.4
               2003 C   10616  2.7  4.8  0.552  ...  0.9  2.2  3.1  0.3  0.2
               2004 C   11176  1.4  3.2  0.442  ...  1.0  1.5  2.4  0.3  0.2
               2005 C   11754  2.3  4.0  0.568  ...  0.8  2.3  3.2  0.4  0.2
               2006 C   12326  1.8  3.3  0.542  ...  0.4  1.8  2.2  0.3  0.2

                               BLK  TOV   PF   PTS  Year
Player         Year Pos
A.C. Green     1986 PF  2302   0.6  1.2  2.8   6.4  1986
               1987 PF  2686   1.0  1.3  2.2  10.8  1987
               1988 PF  3072   0.5  1.5  2.5  11.4  1988
               1989 PF  3506   0.7  1.5  2.1  13.3  1989
               1990 PF  3951   0.6  1.4  2.5  12.9  1990
...                            ...  ...  ...   ...   ...
Željko Rebrača 2002 C   10135  1.0  1.1  2.6   6.9  2002
               2003 C   10616  0.6  1.0  2.6   6.6  2003
               2004 C   11176  0.5  0.7  2.2   3.8  2004
               2005 C   11754  0.7  0.8  2.2   5.8  2005
               2006 C   12326  0.7  0.8  2.0   4.7  2006

[19315 rows x 30 columns]

#### Les deux première colonnes ont été crée par principe lors du merge, nous pouvons les drops sans problème en raison de leur présence

In [13]:
PLAYERS.index = PLAYERS.index.droplevel()

In [14]:
PLAYERS.index = PLAYERS.index.droplevel()

In [15]:
PLAYERS.index = PLAYERS.index.droplevel()

In [31]:
PLAYERS

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
2302,A.C. Green,PF,22,LAL,82,1.0,18.8,2.5,4.7,0.539,...,2.0,2.7,4.6,0.7,0.6,0.6,1.2,2.8,6.4,1986
2686,A.C. Green,PF,23,LAL,79,72.0,28.4,4.0,7.4,0.538,...,2.7,5.1,7.8,1.1,0.9,1.0,1.3,2.2,10.8,1987
3072,A.C. Green,PF,24,LAL,82,64.0,32.1,3.9,7.8,0.503,...,3.0,5.7,8.7,1.1,1.1,0.5,1.5,2.5,11.4,1988
3506,A.C. Green,PF,25,LAL,82,82.0,30.6,4.9,9.2,0.529,...,3.1,5.9,9.0,1.3,1.1,0.7,1.5,2.1,13.3,1989
3951,A.C. Green,PF,26,LAL,82,82.0,33.0,4.7,9.8,0.478,...,3.2,5.5,8.7,1.1,0.8,0.6,1.4,2.5,12.9,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10135,Željko Rebrača,C,29,DET,74,4.0,15.9,2.6,5.1,0.505,...,1.1,2.8,3.9,0.5,0.4,1.0,1.1,2.6,6.9,2002
10616,Željko Rebrača,C,30,DET,30,12.0,16.3,2.7,4.8,0.552,...,0.9,2.2,3.1,0.3,0.2,0.6,1.0,2.6,6.6,2003
11176,Željko Rebrača,C,31,ATL,24,2.0,11.4,1.4,3.2,0.442,...,1.0,1.5,2.4,0.3,0.2,0.5,0.7,2.2,3.8,2004
11754,Željko Rebrača,C,32,LAC,58,2.0,16.0,2.3,4.0,0.568,...,0.8,2.3,3.2,0.4,0.2,0.7,0.8,2.2,5.8,2005
12326,Željko Rebrača,C,33,LAC,29,2.0,14.2,1.8,3.3,0.542,...,0.4,1.8,2.2,0.3,0.2,0.7,0.8,2.0,4.7,2006

In [32]:
PLAYERS.loc[PLAYERS["Player"] == "George Johnson"]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
159,George Johnson,C,31,NJN,81,NaN,26.2,3.1,6.7,0.457,...,2.4,5.1,7.4,2.1,0.7,3.2,2.5,3.9,7.2,1980
160,George Johnson,PF,23,DEN,75,NaN,25.8,4.1,8.7,0.476,...,2.5,5.3,7.8,2.1,1.1,0.9,2.0,3.5,10.2,1980
513,George Johnson,C,32,SAS,82,NaN,23.6,2.0,4.2,0.473,...,2.6,4.7,7.3,1.1,0.6,3.4,1.3,3.3,5.0,1981
514,George Johnson,PF,24,IND,43,NaN,21.6,4.2,9.2,0.462,...,2.3,4.2,6.5,2.0,1.1,0.5,2.0,2.8,10.6,1981
879,George Johnson,C,33,SAS,75,62.0,21.0,1.2,2.6,0.467,...,2.0,4.0,6.1,1.1,0.3,3.1,1.2,3.5,3.0,1982
880,George Johnson,PF,25,IND,59,4.0,12.2,2.0,4.9,0.412,...,1.2,2.5,3.7,0.7,0.6,0.4,1.2,2.5,5.1,1982
1251,George Johnson,C,34,ATL,37,0.0,12.5,0.7,1.5,0.439,...,1.2,2.0,3.2,0.5,0.3,1.6,0.5,1.9,1.7,1983
1252,George Johnson,SF,26,IND,82,64.0,28.0,5.0,10.5,0.477,...,2.1,4.5,6.6,2.7,0.9,0.6,3.0,3.4,11.6,1983
1616,George Johnson,SF,27,IND,81,20.0,25.6,5.1,10.9,0.465,...,1.7,4.0,5.7,2.4,1.0,0.6,2.3,3.2,13.0,1984
1965,George Johnson,C,36,NJN,65,0.0,12.3,0.6,1.2,0.532,...,1.1,1.7,2.8,0.3,0.3,1.2,0.6,2.3,1.6,1985
1966,George Johnson,SF,28,PHI,55,3.0,13.7,1.9,4.8,0.407,...,0.9,2.1,3.0,0.7,0.6,0.3,0.9,1.8,4.8,1985
2346,George Johnson,C,37,SEA,41,0.0,6.4,0.3,0.6,0.522,...,0.6,0.8,1.5,0.3,0.1,0.9,0.3,1.1,0.9,1986
2347,George Johnson,PF,29,WSB,2,0.0,3.5,0.5,1.5,0.333,...,0.5,0.5,1.0,0.0,0.0,0.0,0.5,0.5,2.0,1986

#### Maintenant que nos deux dataframes sont prêts nous pouvons déjà merge ces deux là en selectionnant une méthode 'outer' centré sur les colonnes 'Player' et 'Year'

In [26]:
combined = PLAYERS.merge(MVPS, how = "outer", on = ["Player", "Year"])

In [46]:
MVPS[MVPS["Year"]==2023]

                    Player  Year  Pts Won  Pts Max  Share
685           Nikola Jokić  2023    875.0     1000  0.875
686            Joel Embiid  2023    706.0     1000  0.706
687  Giannis Antetokounmpo  2023    595.0     1000  0.595
688           Devin Booker  2023    216.0     1000  0.216
689            Luka Dončić  2023    146.0     1000  0.146
690           Jayson Tatum  2023     43.0     1000  0.043
691              Ja Morant  2023     10.0     1000  0.010
692          Stephen Curry  2023      4.0     1000  0.004
693             Chris Paul  2023      2.0     1000  0.002
694          DeMar DeRozan  2023      1.0     1000  0.001
695           Kevin Durant  2023      1.0     1000  0.001
696           LeBron James  2023      1.0     1000  0.001

In [34]:
combined.loc[combined["Player"] == "George Johnson"]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
6642,George Johnson,C,31,NJN,81,NaN,26.2,3.1,6.7,0.457,...,2.1,0.7,3.2,2.5,3.9,7.2,1980,NaN,NaN,NaN
6643,George Johnson,PF,23,DEN,75,NaN,25.8,4.1,8.7,0.476,...,2.1,1.1,0.9,2.0,3.5,10.2,1980,NaN,NaN,NaN
6644,George Johnson,C,32,SAS,82,NaN,23.6,2.0,4.2,0.473,...,1.1,0.6,3.4,1.3,3.3,5.0,1981,3.0,690.0,0.004
6645,George Johnson,PF,24,IND,43,NaN,21.6,4.2,9.2,0.462,...,2.0,1.1,0.5,2.0,2.8,10.6,1981,3.0,690.0,0.004
6646,George Johnson,C,33,SAS,75,62.0,21.0,1.2,2.6,0.467,...,1.1,0.3,3.1,1.2,3.5,3.0,1982,NaN,NaN,NaN
6647,George Johnson,PF,25,IND,59,4.0,12.2,2.0,4.9,0.412,...,0.7,0.6,0.4,1.2,2.5,5.1,1982,NaN,NaN,NaN
6648,George Johnson,C,34,ATL,37,0.0,12.5,0.7,1.5,0.439,...,0.5,0.3,1.6,0.5,1.9,1.7,1983,NaN,NaN,NaN
6649,George Johnson,SF,26,IND,82,64.0,28.0,5.0,10.5,0.477,...,2.7,0.9,0.6,3.0,3.4,11.6,1983,NaN,NaN,NaN
6650,George Johnson,SF,27,IND,81,20.0,25.6,5.1,10.9,0.465,...,2.4,1.0,0.6,2.3,3.2,13.0,1984,NaN,NaN,NaN
6651,George Johnson,C,36,NJN,65,0.0,12.3,0.6,1.2,0.532,...,0.3,0.3,1.2,0.6,2.3,1.6,1985,NaN,NaN,NaN
6652,George Johnson,SF,28,PHI,55,3.0,13.7,1.9,4.8,0.407,...,0.7,0.6,0.3,0.9,1.8,4.8,1985,NaN,NaN,NaN
6653,George Johnson,C,37,SEA,41,0.0,6.4,0.3,0.6,0.522,...,0.3,0.1,0.9,0.3,1.1,0.9,1986,NaN,NaN,NaN
6654,George Johnson,PF,29,WSB,2,0.0,3.5,0.5,1.5,0.333,...,0.0,0.0,0.0,0.5,0.5,2.0,1986,NaN,NaN,NaN

#### Ici, le problème chronique des données trop ancienne, est l'absence des colonnes "Pts Won", "Pts Max" et "Share", nous pouvons les remplacer directement par 0 qui n'a pas d'impacte sur la prédiction

In [35]:
combined[["Pts Won", "Pts Max", "Share"]] = combined[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [36]:
TEAMS.head(30)

,index,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,61,21,.744,—,113.5,105.7,7.37,1980,Boston Celtics*
1,1,59,23,.720,2.0,109.1,104.9,4.04,1980,Philadelphia 76ers*
2,2,39,43,.476,22.0,107.0,109.5,-2.27,1980,Washington Bullets*
3,3,39,43,.476,22.0,114.0,115.1,-0.96,1980,New York Knicks
4,4,34,48,.415,27.0,108.3,109.5,-0.98,1980,New Jersey Nets
5,5,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,1980,Central Division
6,6,50,32,.610,—,104.5,101.6,2.83,1980,Atlanta Hawks*
7,7,41,41,.500,9.0,110.8,110.6,0.27,1980,Houston Rockets*
8,8,41,41,.500,9.0,119.4,119.7,-0.24,1980,San Antonio Spurs*
9,9,37,45,.451,13.0,111.2,111.9,-0.54,1980,Indiana Pacers
10,10,37,45,.451,13.0,114.1,113.8,0.43,1980,Cleveland Cavaliers
11,11,16,66,.195,34.0,108.9,117.2,-7.57,1980,Detroit Pistons
12,0,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,1980,Midwest Division
13,1,49,33,.598,—,110.1,106.1,3.57,1980,Milwaukee Bucks*
14,2,47,35,.573,2.0,108.0,104.9,2.82,1980,Kansas City Kings*
15,3,30,52,.366,19.0,108.3,112.7,-4.22,1980,Denver Nuggets
16,4,30,52,.366,19.0,107.5,110.2,-2.63,1980,Chicago Bulls
17,5,24,58,.293,25.0,102.4,108.4,-5.71,1980,Utah Jazz
18,6,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,1980,Pacific Division
19,7,60,22,.732,—,115.1,109.2,5.40,1980,Los Angeles Lakers*
20,8,56,26,.683,4.0,108.5,103.8,4.24,1980,Seattle SuperSonics*
21,9,55,27,.671,5.0,111.1,107.5,3.25,1980,Phoenix Suns*
22,10,38,44,.463,22.0,102.5,103.3,-0.87,1980,Portland Trail Blazers*
23,11,35,47,.427,25.0,107.6,111.7,-3.97,1980,San Diego Clippers
24,12,24,58,.293,36.0,103.6,108.0,-4.20,1980,Golden State Warriors
25,0,62,20,.756,—,109.9,104.0,6.05,1981,Boston Celtics*
26,1,62,20,.756,—,111.7,103.8,7.76,1981,Philadelphia 76ers*
27,2,50,32,.610,12.0,107.9,106.3,2.00,1981,New York Knicks*
28,3,39,43,.476,23.0,105.6,105.6,0.42,1981,Washington Bullets
29,4,24,58,.293,38.0,106.9,113.0,-5.15,1981,New Jersey Nets

#### Lors du scrapping du dataframe TEAMS, nous avons effectué un scrap total qui a aussi exporter les titres de chaque section, à savoir les divisions qui sont inutiles à notre future prédiction, nous pouvons donc les drop

In [37]:
TEAMS = TEAMS[~TEAMS["W"].str.contains("Division")]

In [38]:
TEAMS.head(30)

,index,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,61,21,.744,—,113.5,105.7,7.37,1980,Boston Celtics*
1,1,59,23,.720,2.0,109.1,104.9,4.04,1980,Philadelphia 76ers*
2,2,39,43,.476,22.0,107.0,109.5,-2.27,1980,Washington Bullets*
3,3,39,43,.476,22.0,114.0,115.1,-0.96,1980,New York Knicks
4,4,34,48,.415,27.0,108.3,109.5,-0.98,1980,New Jersey Nets
6,6,50,32,.610,—,104.5,101.6,2.83,1980,Atlanta Hawks*
7,7,41,41,.500,9.0,110.8,110.6,0.27,1980,Houston Rockets*
8,8,41,41,.500,9.0,119.4,119.7,-0.24,1980,San Antonio Spurs*
9,9,37,45,.451,13.0,111.2,111.9,-0.54,1980,Indiana Pacers
10,10,37,45,.451,13.0,114.1,113.8,0.43,1980,Cleveland Cavaliers
11,11,16,66,.195,34.0,108.9,117.2,-7.57,1980,Detroit Pistons
13,1,49,33,.598,—,110.1,106.1,3.57,1980,Milwaukee Bucks*
14,2,47,35,.573,2.0,108.0,104.9,2.82,1980,Kansas City Kings*
15,3,30,52,.366,19.0,108.3,112.7,-4.22,1980,Denver Nuggets
16,4,30,52,.366,19.0,107.5,110.2,-2.63,1980,Chicago Bulls
17,5,24,58,.293,25.0,102.4,108.4,-5.71,1980,Utah Jazz
19,7,60,22,.732,—,115.1,109.2,5.40,1980,Los Angeles Lakers*
20,8,56,26,.683,4.0,108.5,103.8,4.24,1980,Seattle SuperSonics*
21,9,55,27,.671,5.0,111.1,107.5,3.25,1980,Phoenix Suns*
22,10,38,44,.463,22.0,102.5,103.3,-0.87,1980,Portland Trail Blazers*
23,11,35,47,.427,25.0,107.6,111.7,-3.97,1980,San Diego Clippers
24,12,24,58,.293,36.0,103.6,108.0,-4.20,1980,Golden State Warriors
25,0,62,20,.756,—,109.9,104.0,6.05,1981,Boston Celtics*
26,1,62,20,.756,—,111.7,103.8,7.76,1981,Philadelphia 76ers*
27,2,50,32,.610,12.0,107.9,106.3,2.00,1981,New York Knicks*
28,3,39,43,.476,23.0,105.6,105.6,0.42,1981,Washington Bullets
29,4,24,58,.293,38.0,106.9,113.0,-5.15,1981,New Jersey Nets
31,6,60,22,.732,—,113.1,105.9,7.14,1981,Milwaukee Bucks*
32,7,45,37,.549,15.0,109.0,107.0,2.34,1981,Chicago Bulls*
33,8,44,38,.537,16.0,107.6,106.2,1.72,1981,Indiana Pacers*

#### Même problème qu'avant concernant les astérisques, nous pouvons les enlever de la même manière

In [39]:
TEAMS["Team"] = TEAMS["Team"].str.replace("*", "", regex = False)

ETAPE EN PLUS POUR L'ANNEE EN COURS

En effet, dans l'année en cours, on remarque que les noms des équipes sont suivis d'un chiffre en parenthèse

In [40]:

TEAMS['Team'] = TEAMS['Team'].apply(lambda x: re.sub(r'\(\d+\)', '', x).strip())

In [41]:
TEAMS.head(30)

,index,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,61,21,.744,—,113.5,105.7,7.37,1980,Boston Celtics
1,1,59,23,.720,2.0,109.1,104.9,4.04,1980,Philadelphia 76ers
2,2,39,43,.476,22.0,107.0,109.5,-2.27,1980,Washington Bullets
3,3,39,43,.476,22.0,114.0,115.1,-0.96,1980,New York Knicks
4,4,34,48,.415,27.0,108.3,109.5,-0.98,1980,New Jersey Nets
6,6,50,32,.610,—,104.5,101.6,2.83,1980,Atlanta Hawks
7,7,41,41,.500,9.0,110.8,110.6,0.27,1980,Houston Rockets
8,8,41,41,.500,9.0,119.4,119.7,-0.24,1980,San Antonio Spurs
9,9,37,45,.451,13.0,111.2,111.9,-0.54,1980,Indiana Pacers
10,10,37,45,.451,13.0,114.1,113.8,0.43,1980,Cleveland Cavaliers
11,11,16,66,.195,34.0,108.9,117.2,-7.57,1980,Detroit Pistons
13,1,49,33,.598,—,110.1,106.1,3.57,1980,Milwaukee Bucks
14,2,47,35,.573,2.0,108.0,104.9,2.82,1980,Kansas City Kings
15,3,30,52,.366,19.0,108.3,112.7,-4.22,1980,Denver Nuggets
16,4,30,52,.366,19.0,107.5,110.2,-2.63,1980,Chicago Bulls
17,5,24,58,.293,25.0,102.4,108.4,-5.71,1980,Utah Jazz
19,7,60,22,.732,—,115.1,109.2,5.40,1980,Los Angeles Lakers
20,8,56,26,.683,4.0,108.5,103.8,4.24,1980,Seattle SuperSonics
21,9,55,27,.671,5.0,111.1,107.5,3.25,1980,Phoenix Suns
22,10,38,44,.463,22.0,102.5,103.3,-0.87,1980,Portland Trail Blazers
23,11,35,47,.427,25.0,107.6,111.7,-3.97,1980,San Diego Clippers
24,12,24,58,.293,36.0,103.6,108.0,-4.20,1980,Golden State Warriors
25,0,62,20,.756,—,109.9,104.0,6.05,1981,Boston Celtics
26,1,62,20,.756,—,111.7,103.8,7.76,1981,Philadelphia 76ers
27,2,50,32,.610,12.0,107.9,106.3,2.00,1981,New York Knicks
28,3,39,43,.476,23.0,105.6,105.6,0.42,1981,Washington Bullets
29,4,24,58,.293,38.0,106.9,113.0,-5.15,1981,New Jersey Nets
31,6,60,22,.732,—,113.1,105.9,7.14,1981,Milwaukee Bucks
32,7,45,37,.549,15.0,109.0,107.0,2.34,1981,Chicago Bulls
33,8,44,38,.537,16.0,107.6,106.2,1.72,1981,Indiana Pacers

In [42]:
TEAMS["Team"].unique()

array(['Boston Celtics', 'Philadelphia 76ers', 'Washington Bullets',
       'New York Knicks', 'New Jersey Nets', 'Atlanta Hawks',
       'Houston Rockets', 'San Antonio Spurs', 'Indiana Pacers',
       'Cleveland Cavaliers', 'Detroit Pistons', 'Milwaukee Bucks',
       'Kansas City Kings', 'Denver Nuggets', 'Chicago Bulls',
       'Utah Jazz', 'Los Angeles Lakers', 'Seattle SuperSonics',
       'Phoenix Suns', 'Portland Trail Blazers', 'San Diego Clippers',
       'Golden State Warriors', 'Dallas Mavericks',
       'Los Angeles Clippers', 'Sacramento Kings', 'Charlotte Hornets',
       'Miami Heat', 'Orlando Magic', 'Minnesota Timberwolves',
       'Toronto Raptors', 'Vancouver Grizzlies', 'Washington Wizards',
       'Memphis Grizzlies', 'New Orleans Hornets', 'Charlotte Bobcats',
       'New Orleans/Oklahoma City Hornets', 'Oklahoma City Thunder',
       'Brooklyn Nets', 'New Orleans Pelicans'], dtype=object)

In [43]:
combined["Tm"].unique()

array(['LAL', 'PHO', 'DAL', 'MIA', 'CLE', 'WSB', 'MIL', 'CHI', 'GSW',
       'IND', 'WAS', 'MIN', 'BOS', 'ATL', 'HOU', 'DEN', 'ORL', 'NOH',
       'TOR', 'SAC', 'CHO', 'PHI', 'POR', 'DET', 'TOT', 'OKC', 'UTA',
       'VAN', 'SEA', 'NJN', 'NOK', 'LAC', 'CHA', 'MEM', 'NYK', 'SDC',
       'NOP', 'BRK', 'SAS', 'CHH', 'KCK'], dtype=object)

#### Nous rentrons dans la phase finale du cleaning, donc le merge final avec le dataframe TEAMS, cependant, étant donné que nous le centrant sur "Players" et "Years", nous devons effectuer des modifications sur le nom des équipes dans notre dataset précédent qui note les teams par abbréviation et non par nom complet.

#### Nous avons crées un fichier nicknames.txt avec comme contenu 'Abbreviation' = 'Nom' sous forme de dictionnaire pour remplacer chaque abbréviation par leur nom complet pour un merge efficace.

In [44]:
nicknames = {}

with open("nicknames.txt") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev, name = line.replace("\n", "").split(",")
        nicknames[abbrev] = name

In [45]:
combined["Team"] = combined["Tm"].map(nicknames)

In [46]:
combined["Team"].unique()

array(['Los Angeles Lakers', 'Phoenix Suns', 'Dallas Mavericks',
       'Miami Heat', 'Cleveland Cavaliers', 'Washington Bullets',
       'Milwaukee Bucks', 'Chicago Bulls', 'Golden State Warriors',
       'Indiana Pacers', 'Washington Wizards', 'Minnesota Timberwolves',
       'Boston Celtics', 'Atlanta Hawks', 'Houston Rockets',
       'Denver Nuggets', 'Orlando Magic', 'New Orleans Hornets',
       'Toronto Raptors', 'Sacramento Kings', 'Charlotte Hornets',
       'Philadelphia 76ers', 'Portland Trail Blazers', 'Detroit Pistons',
       nan, 'Oklahoma City Thunder', 'Utah Jazz', 'Vancouver Grizzlies',
       'Seattle SuperSonics', 'New Jersey Nets',
       'New Orleans/Oklahoma City Hornets', 'Los Angeles Clippers',
       'Charlotte Bobcats', 'Memphis Grizzlies', 'New York Knicks',
       'New Orleans Pelicans', 'Brooklyn Nets', 'San Antonio Spurs'],
      dtype=object)

#### Nous pouvons enfin concater nos 2 derniers dataframes avec le dataframe TEAMS fraichement préparé

In [47]:
FinalWorkDF = combined.merge(TEAMS, how = "inner", on = ["Team", "Year"])

In [48]:
FinalWorkDF

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Share,Team,index,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,22,LAL,82,1.0,18.8,2.5,4.7,0.539,...,0.000,Los Angeles Lakers,8,62,20,.756,—,117.3,109.5,6.84
1,Byron Scott,SG,24,LAL,76,62.0,28.8,6.7,13.0,0.513,...,0.000,Los Angeles Lakers,8,62,20,.756,—,117.3,109.5,6.84
2,James Worthy,SF,24,LAL,75,73.0,32.7,8.4,14.5,0.579,...,0.009,Los Angeles Lakers,8,62,20,.756,—,117.3,109.5,6.84
3,Jerome Henderson,C,26,LAL,1,0.0,3.0,2.0,3.0,0.667,...,0.000,Los Angeles Lakers,8,62,20,.756,—,117.3,109.5,6.84
4,Kareem Abdul-Jabbar,C,38,LAL,79,79.0,33.3,9.6,16.9,0.564,...,0.173,Los Angeles Lakers,8,62,20,.756,—,117.3,109.5,6.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18889,Mike Gale,PG,29,SAS,67,NaN,22.0,2.6,5.6,0.454,...,0.000,San Antonio Spurs,8,41,41,.500,9.0,119.4,119.7,-0.24
18890,Paul Griffin,C,26,SAS,82,NaN,22.1,2.1,3.8,0.553,...,0.000,San Antonio Spurs,8,41,41,.500,9.0,119.4,119.7,-0.24
18891,Sylvester Norris,C,22,SAS,17,NaN,11.1,1.1,2.5,0.419,...,0.000,San Antonio Spurs,8,41,41,.500,9.0,119.4,119.7,-0.24
18892,Tim Bassett,PF,28,SAS,12,NaN,13.7,1.0,2.8,0.353,...,0.000,San Antonio Spurs,8,41,41,.500,9.0,119.4,119.7,-0.24
18893,Wiley Peck,SF,22,SAS,52,NaN,12.1,1.4,3.3,0.432,...,0.000,San Antonio Spurs,8,41,41,.500,9.0,119.4,119.7,-0.24

In [49]:
FinalWorkDF.dtypes

Player      object
Pos         object
Age          int64
Tm          object
G            int64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
index        int64
W           object
L           object
W/L%        object
GB          object
PS/G        object
PA/G        object
SRS         object
dtype: object

#### Certaines statistiques restent en "object" qui peuvent poser un problème, nous allons donc les convertir en extension numérique tout en laissant les variables s'apparentant à un string en object comme par exemple 'Player' via le paramètre " errors = 'ignore' "

In [50]:
FinalWorkDF = FinalWorkDF.apply(pd.to_numeric, errors = "ignore")

In [51]:
FinalWorkDF.dtypes

Player      object
Pos         object
Age          int64
Tm          object
G            int64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
index        int64
W            int64
L            int64
W/L%       float64
GB          object
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [52]:
FinalWorkDF["GB"].unique()

array(['—', '5.0', '14.0', '23.0', '7.0', '40.0', '42.0', '18.0', '6.0',
       '24.0', '26.0', '37.0', '29.0', '21.0', '28.0', '25.0', '8.0',
       '19.0', '3.0', '1.0', '13.0', '17.0', '15.0', '9.0', '2.0', '35.0',
       '20.0', '11.0', '16.0', '41.0', '12.0', '43.0', '50.0', '10.0',
       '30.0', '34.0', '4.0', '1.5', '22.0', '51.0', '36.0', '39.0',
       '18.5', '31.0', '48.0', '38.0', '46.0', '10.5', '32.0', '27.0',
       '33.0', '34.5', '21.5', '45.0', '23.5', '22.5', '8.5', '25.5',
       '24.5', '3.5', '20.5', '11.5', '44.0', '52.0', '56.0', '2.5',
       '12.5', '53.0', '47.0', '4.5', '32.5', '7.5', '14.5'], dtype=object)

#### Nous pouvons voir que la statistique "GB" qui correspond à "Games Back" reste en "object", après inspection nous pouvons voir que ceci est dû au faite qu'il y a une valeur '—' qui veut tout simplement dire que l'équipe en question est en tête, donc nous pouvons remplacer cette valeur par '0.0'

In [53]:
FinalWorkDF["GB"] = FinalWorkDF["GB"].str.replace("—", "0.0")

In [54]:
FinalWorkDF["GB"].unique()

array(['0.0', '5.0', '14.0', '23.0', '7.0', '40.0', '42.0', '18.0', '6.0',
       '24.0', '26.0', '37.0', '29.0', '21.0', '28.0', '25.0', '8.0',
       '19.0', '3.0', '1.0', '13.0', '17.0', '15.0', '9.0', '2.0', '35.0',
       '20.0', '11.0', '16.0', '41.0', '12.0', '43.0', '50.0', '10.0',
       '30.0', '34.0', '4.0', '1.5', '22.0', '51.0', '36.0', '39.0',
       '18.5', '31.0', '48.0', '38.0', '46.0', '10.5', '32.0', '27.0',
       '33.0', '34.5', '21.5', '45.0', '23.5', '22.5', '8.5', '25.5',
       '24.5', '3.5', '20.5', '11.5', '44.0', '52.0', '56.0', '2.5',
       '12.5', '53.0', '47.0', '4.5', '32.5', '7.5', '14.5'], dtype=object)

In [55]:
FinalWorkDF["GB"] = pd.to_numeric(FinalWorkDF["GB"])

In [56]:
FinalWorkDF["GB"].unique()

array([ 0. ,  5. , 14. , 23. ,  7. , 40. , 42. , 18. ,  6. , 24. , 26. ,
       37. , 29. , 21. , 28. , 25. ,  8. , 19. ,  3. ,  1. , 13. , 17. ,
       15. ,  9. ,  2. , 35. , 20. , 11. , 16. , 41. , 12. , 43. , 50. ,
       10. , 30. , 34. ,  4. ,  1.5, 22. , 51. , 36. , 39. , 18.5, 31. ,
       48. , 38. , 46. , 10.5, 32. , 27. , 33. , 34.5, 21.5, 45. , 23.5,
       22.5,  8.5, 25.5, 24.5,  3.5, 20.5, 11.5, 44. , 52. , 56. ,  2.5,
       12.5, 53. , 47. ,  4.5, 32.5,  7.5, 14.5])

#### Inspectons les valeurs nulles qui peuvent poser un problème lors de la prédiction (A faire)

In [57]:
pd.isna(FinalWorkDF).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS          498
MP            0
FG            0
FGA           0
FG%          75
3P            0
3PA           0
3P%        2791
2P            0
2PA           0
2P%         122
eFG%         75
FT            0
FTA           0
FT%         661
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
index         0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [58]:
FinalWorkDF[pd.isna(FinalWorkDF["GS"])]["Year"].unique()

array([1980, 1981], dtype=int64)

#### Nous pouvons voir que la statistiques "GS" qui correspond à la titularisation d'un joueur est manquante sur les années 1980 et 1981, qui reste quand même une statistiques importantes à la prédiction du MVP, par conséquent nous pouvons drop ces deux années précises.

In [59]:
FinalWorkDF.drop(FinalWorkDF.loc[FinalWorkDF["Year"] == 1980].index, inplace = True)

In [60]:
FinalWorkDF.drop(FinalWorkDF.loc[FinalWorkDF["Year"] == 1981].index, inplace = True)

In [61]:
pd.isna(FinalWorkDF).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          75
3P            0
3PA           0
3P%        2680
2P            0
2PA           0
2P%         122
eFG%         75
FT            0
FTA           0
FT%         653
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
index         0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

#### Nous pouvons noter que quelques statistiques restent nulles, cependant c'est facilement expliquer par leurs calcule
#### En effet le calcule pour la colonne 3P% est calculé par le ratio entre 3P (3 points goal) et 3PA (3 points attempt), donc si le joueur n'a jamais tenté un tire à 3 points sa colonne sera une division par 0 donc remplacé par un NA

In [62]:
FinalWorkDF[pd.isnull(FinalWorkDF["3P%"])][["Player", "3PA"]]

                  Player  3PA
3       Jerome Henderson  0.0
5            Kurt Rambis  0.0
12     Pétur Guðmundsson  0.0
18      Frank Brickowski  0.0
21           Kurt Rambis  0.0
...                  ...  ...
18849     Evan Eschmeyer  0.0
18850   Gheorghe Mureșan  0.0
18852      Jim McIlvaine  0.0
18858   Mark Hendrickson  0.0
18859       Michael Cage  0.0

[2680 rows x 2 columns]

#### Nous pouvons remplacer ces valeurs manquantes par 0, ce qui n'est pas totalement vraie mais nous pouvons quand même remplacer car ca n'influe pas sur la prédiction finale qui est de prédire le MVP, et le MVP sera un joueur ayant marqué des buts à 3 points

#### Nous pouvons voir le même constat pour les autres colonnes comme "FT%" et "FG%" qui se calcule de la meme manière avec une division de deux colonnes

In [63]:
FinalWorkDF = FinalWorkDF.fillna(0)

In [64]:
pd.isna(FinalWorkDF).sum()

Player     0
Pos        0
Age        0
Tm         0
G          0
GS         0
MP         0
FG         0
FGA        0
FG%        0
3P         0
3PA        0
3P%        0
2P         0
2PA        0
2P%        0
eFG%       0
FT         0
FTA        0
FT%        0
ORB        0
DRB        0
TRB        0
AST        0
STL        0
BLK        0
TOV        0
PF         0
PTS        0
Year       0
Pts Won    0
Pts Max    0
Share      0
Team       0
index      0
W          0
L          0
W/L%       0
GB         0
PS/G       0
PA/G       0
SRS        0
dtype: int64

In [65]:
FinalStat = sqlite3.connect('finalstat.sqlite')

In [66]:
FinalWorkDF.to_sql("FinalStat", con = FinalStat,if_exists="replace")

18352

#### Nous pouvons fermer les fichiers SQL en cours d'execution

In [67]:
TEAMScon.close()

In [68]:
PLAYERScon.close()

In [69]:
FinalStat.close()

In [70]:
MVPcon.close()